DROP TABLE IF EXISTS uczestnicy CASCADE;

DROP TABLE IF EXISTS autor CASCADE;

DROP TABLE IF EXISTS kategorie CASCADE;

DROP TABLE IF EXISTS pytania CASCADE;

DROP TABLE IF EXISTS autorzy_pytan CASCADE;

DROP TABLE IF EXISTS adresy CASCADE;

DROP TABLE IF EXISTS turnieje CASCADE;

DROP TABLE IF EXISTS typy_kar CASCADE;

DROP TABLE IF EXISTS zespoly CASCADE;

DROP TABLE IF EXISTS role CASCADE;

DROP TABLE IF EXISTS sklady_w_zespolach CASCADE;

DROP TABLE IF EXISTS kary_dla_zespolow CASCADE;

DROP TABLE IF EXISTS nagrody CASCADE;

DROP TABLE IF EXISTS nagrody_w_turniejach CASCADE;

DROP TABLE IF EXISTS zmiany CASCADE;

DROP TABLE IF EXISTS poprawne_odpowiedzi CASCADE;

DROP TABLE IF EXISTS organizacja CASCADE;

DROP TABLE IF EXISTS pytania_na_turniejach CASCADE;

